language: java

dist: trusty



jdk:

- oraclejdk8



sudo: false

script:

- "mvn evosuite:generate"

- "mvn evosuite:export"

- "mvn cobertura:cobertura"

- "mvn test"
# after_success:

# - bash <(curl -s https://codecov.io/bash)
